# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: Cyril Zhang
description: I like internet things, computer things, math things, and writing things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "cglzhng.github.io" # the base hostname & protocol for your site
include: [_pages]

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title/
